<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.6.6 on win32)" generated="20210730 20:04:43.021" rpa="false">
<suite id="s1" name="RF tests for search field 5 links" source="C:\Users\alex\PycharmProjects\robot_tests_for_ps_18525116133_4242_PS\RF_tests_for_search_field_5_links.robot">
<kw name="Open Browser" library="SeleniumLibrary" type="setup">
<doc>Opens a new browser instance to the optional ``url``.</doc>
<msg timestamp="20210730 20:04:43.276" level="INFO">Opening browser 'firefox' to base url 'None'.</msg>
<msg timestamp="20210730 20:04:43.278" level="INFO">Firefox driver log is always forced to to: C:\Users\alex\PycharmProjects\robot_tests_for_ps_18525116133_4242_PS\geckodriver-1.log</msg>
<status status="PASS" starttime="20210730 20:04:43.276" endtime="20210730 20:04:49.561"></status>
</kw>
<test id="s1-t1" name="Check_search_results_via_using_csv_file_data using ${links_for_search_form}">
<status status="FAIL" starttime="20210730 20:04:49.561" endtime="20210730 20:04:49.563" critical="yes">Test case contains no keywords.</status>
</test>
<kw name="Close All Browsers" library="SeleniumLibrary" type="teardown">
<doc>Closes all open browsers and resets the browser cache.</doc>
<status status="PASS" starttime="20210730 20:04:49.564" endtime="20210730 20:04:50.200"></status>
</kw>
<status status="FAIL" starttime="20210730 20:04:43.023" endtime="20210730 20:04:50.200"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="RF tests for search field 5 links">RF tests for search field 5 links</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210730 20:04:43.263" level="ERROR">Error in file 'C:\Users\alex\PycharmProjects\robot_tests_for_ps_18525116133_4242_PS\RF_tests_for_search_field_5_links.robot' on line 3: Resource file '..\Robot_Tests_185.25.116.133_4242_PS\Resources\search_results.robot' does not exist.</msg>
<msg timestamp="20210730 20:04:43.275" level="ERROR">Calling method '_start_suite' of listener 'DataDriver' failed: FileNotFoundError: File attribute was not a full path. Tried to find C:\Users\alex\PycharmProjects\robot_tests_for_ps_18525116133_4242_PS\../Robot_Tests_185.25.116.133_4242_PS/TestData/PS_search_links_csv_file_5_links.csv but file does not exist.</msg>
</errors>
</robot>
